name: client
on:
  push:
    tags:
      - '*'
jobs:
  # runs_script:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run script file
  #   run: chmod +x ./deploy.sh && ./deploy.sh
  #   shell: bash
  docker:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout/@v2
      - name: Run scripts
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

